//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Voting_Syste_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartyList
    {
        public int ID { get; set; }
        public string Party_Name { get; set; }
        public long Counter { get; set; }
    }
}
